#ifndef MQTTSTATEMIRROR_GLOBAL_H
#define MQTTSTATEMIRROR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MQTTSTATEMIRROR_LIBRARY)
#  define MQTTSTATEMIRRORSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MQTTSTATEMIRRORSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MQTTSTATEMIRROR_GLOBAL_H
